[general]
repository = "https://thunderstore.io"

[package]
namespace = "smrkn"
name = "Minimap"
versionNumber = "0.1.0"
description = "Flexible and customisable minimap mod."
websiteUrl = "https://github.com/csh/lens-island-minimap"

[package.dependencies]
BepInEx-BepInExPack_LensIsland = "5.4.2303"

[build]
icon = "icon.png"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[[build.copy]]
source = "Minimap/bin/Release/Minimap.dll"
target = "BepInEx/plugins/Minimap.dll"

# We embed the default overlay in the DLL

[publish]
categories = [
    "mods"
]

communities = [
    "lens-island"
]
